version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    env_file:
      - ./back-end/.env    
    ports:
      - "3306:3306"
    networks:
      - neo
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
      - "./mariadb-data/logs:/var/lib/mysql/logs/"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1 
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - neo

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   
      - "15672:15672" 
    env_file:
      - ./back-end/.env
    networks:
      - neo


  nestjs:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: back-neo
    ports:
      - "8000:8000"
    env_file:
      - ./back-end/.env 
    volumes:
      - logs:/app/logs
    depends_on:
      - mariadb
    networks:
      - neo

  front-end:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    container_name: front-end
    ports:
      - "3000:3000"
    depends_on:
      - nestjs
    networks:
      - neo
    

networks:
  neo:
    driver: bridge

volumes:
  mariadb_data:
  logs:
